id = "gt"
name = "GT"
description = "Graph Text (.gt) syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["marsgpl"]
repository = "https://github.com/marsgpl/zed-gt-extension"

[grammars.gt]
repository = "https://github.com/marsgpl/zed-gt-extension"
commit = "059bb7f343874ea82cac699a71178dbbf3c35419"
