id = "gt"
name = "GT"
description = "Graph Text (.gt) syntax highlighting"
version = "0.1.0"
schema_version = 1
authors = ["marsgpl"]
repository = ""

[grammars.gt]
repository = "https://github.com/marsgpl/tree-sitter-gt"
commit = "PLACEHOLDER"
